// 
// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file was generated by server/scripts/generate-types.ts
// 

export interface User {
    id: number;
    username: string;
    password: string;
    role: string;
    name?: string;
    email?: string;
    phone?: string;
}

export interface AuditLog {
    id: number;
    user_id?: number;
    username?: string;
    action: string;
    details?: string;
    ip_address?: string;
    created_at: string;
}

export interface FactScore {
    id: number;
    gender?: string;
    race_ethnicity?: string;
    parental_education?: string;
    math?: string;
    math_score?: number;
    reading?: string;
    reading_score?: number;
    writing?: string;
    writing_score?: number;
}

